// <auto-generated />
namespace Driver.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_app_version : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_app_version));
        
        string IMigrationMetadata.Id
        {
            get { return "201608010233000_add_app_version"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
