// <auto-generated />
namespace Driver.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class change_property_of_appversion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_property_of_appversion));
        
        string IMigrationMetadata.Id
        {
            get { return "201608010619202_change_property_of_appversion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
